#!make

# tough aliquot numbers, "Lehmer's five" etc.
# @(#) $Id$
# 2018-04-15, Georg Fischer

all: wget binary
#----------
wget:
	wget https://oeis.org/A216072/b216072.txt
binary:
	perl a216072.pl b216072.txt
#-----
	