#!/bin/make

# for three.js experiments of fasces
# @(#) $Id$
# 2018-02-18, Georg Fischer

all: 
	echo either make deploy-windows or make deploy-linux
deploy-windows:
	cp -v *.js *.html c:/users/gfis/xampp/htdocs/threejs
deploy-linux:
	sudo cp -v *.js *.html /var/www/html/threejs
	