#!perl

# hapy_blocks - generate blocks with Hadamard opacities/colors
# @(#) $Id$
# 2025-08-09, Georg Fischer: copied from hapy_empty.pl; *VF=44
#:#
#:# Usage:
#:#   perl hapy_blocks.pl [-d debug] planes.tmp > hapyramid_blocks.js
#:#       -d 0=none, 1=some, 2=more debuging output
#:#       -m max. edge length (default 22)
#----------------
use strict;
use warnings;
use integer;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday) = gmtime (time);
my $utc_stamp = sprintf ("%04d-%02d-%02dT%02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);

my $debug = 0;
my $max_edge = 22;
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } elsif ($opt  =~ m{e}) {
        $max_edge  = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt
#--------
# read the matrices
my @planes = ();
my @plane = ( # default planes[0]
 [ 1, 1 ],
 [ 1, 0 ]
);

my $ipla = -1;
while(<>) {
  s/\s+\Z//;
  my $line = $_;
  #                1   1
  if ($line =~ m{\[(\d+)\]}) { # plane header line
    $ipla = $1;
    push(@planes, [@plane]); # previous accumulated plane
    @plane = ();
    #                          (1       1
  } elsif ($line =~ m{\A[\(\,]\(([01\,\-]+)}) { # line with matrix elements
    my @terms = map {
          if ($_ ne "1") {
            $_ = 0;
          }
          $_
        } split(/ *\, */, $1);
    push(@plane, [@terms]);
  }
} # while <>
push(@planes, [@plane]); # last accumulated plane
#----
my $displ = 50;
print <<"GFis";
/**
  hapyramid_blocks.js - Coordinates of the blocks for the Hadamard pyramid
  \@(#) \$Id\$
  Generated by hapy_empty.pl at $utc_stamp
*/  
var displ  = $displ;
var vec_pyramid = 
//   aazzxxyy   aazzxxyy   aazzxxyy   aazzxxyy,  aa=opacity 0..15
GFis

my $sep = "[";
my $incr = 0;
for (my $el = 2; $el <= $max_edge; $el += 2) {
  my $el2 = $el / 2;
  print "\n  // plane 4*$el2\n  "; # start next plane on a new line
  $incr ++; 
  my $y = $displ + $max_edge/4 - $incr;
  for (my $row = 0; $row < $el; $row ++) {
    my $x = - $incr + $row + $displ;
    for (my $col = 0; $col < $el; $col ++) {
      if ($el == $max_edge || $row == 0 || $row == $el - 1 || ($col == 0 || $col == $el - 1)) {
        my $z = - $incr + $col + $displ;
        my $opac = (($row + $col) % 16) * 6;
        my $block  =  $opac * 1000000 + $z * 10000 + $x * 100 + $y;
        print "$sep" . sprintf("%8d", $block);
        $sep = ",";
      }
    } # for $col
  } # for $row
} # for $el
print <<"GFis";

  ];
GFis
#--------
__DATA__
/**
  hapyramid_blocks.js - coordinates of the blocks for the Hadamard pyramid
  @(#) $Id$
  2025-08-08: Georg Fischer
*/  
var displ  = 50;
var vec_pyramid = 
//   aazzxxyy   aazzxxyy   aazzxxyy   aazzxxyy,  aa=opacity 0..15
	[              1515150,   1515050
	,              1505150,  15505050 // <- this is the center
	,   2494949,   2495049,   2495149,   2495249
	,   2504949,   2505049,   2505149,   2505249
	,   2514949,   2515049,   2515149,   2515249
	,   2524949,   2525049,   2525149,   2525249
	];
