#!perl

print <<"GFis";
# Table of n, a(n) for n = 0..1000
# A323186 a(0) = 0, a'(0) = 0, a''(0) = 1, a''(1) = -1, a(n) = a(n-1) + a'(n), a'(n) = a'(n-1) + a''(n), a''(n) = -a''(n-1) if a(n-2) = 0, or else a''(n-1).
# "Bad driver's sequence"
# Generated by Perl
# Georg Fischer, Feb 14, 2019
0 0
1 -1
2 -1
GFis
my @a = (0, -1, -1);
for my $n (scalar(@a)..1000) {
    if ($a[$n - 2] == 0) {
        $a[$n] = $a[$n - 1] + &as($n - 1) - &ass($n - 1);
    } else { 
        $a[$n] = $a[$n - 1] + &as($n - 1) + &ass($n - 1);
    }
    print "$n $a[$n]\n";
} # for n
sub as  { my ($n) = @_; return $a[$n]  -  $a[$n - 1]; } 
sub ass { my ($n) = @_; return &as($n) - &as($n - 1); } 
